// <auto-generated />
using System;
using DevIO.Domain.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevIO.Domain.Migrations
{
    [DbContext(typeof(CatalogoDbContext))]
    [Migration("20210803024546_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevIO.Domain.Models.Autor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Celular");

                    b.Property<string>("Cpf");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Autors");
                });

            modelBuilder.Entity("DevIO.Domain.Models.Editora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cnpj");

                    b.Property<string>("Endereco");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Editoras");
                });

            modelBuilder.Entity("DevIO.Domain.Models.Livro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AutorId");

                    b.Property<Guid?>("AutorId1");

                    b.Property<DateTime>("DataLancamento");

                    b.Property<string>("Edicao");

                    b.Property<int>("EditoraId");

                    b.Property<Guid?>("EditoraId1");

                    b.Property<string>("NomeDoLivro");

                    b.HasKey("Id");

                    b.HasIndex("AutorId1");

                    b.HasIndex("EditoraId1");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("DevIO.Domain.Models.Livro", b =>
                {
                    b.HasOne("DevIO.Domain.Models.Autor", "Autor")
                        .WithMany("Livros")
                        .HasForeignKey("AutorId1");

                    b.HasOne("DevIO.Domain.Models.Editora", "Editora")
                        .WithMany("Livros")
                        .HasForeignKey("EditoraId1");
                });
#pragma warning restore 612, 618
        }
    }
}
